name: Deploy to Server

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build
        run: go build -o nevermade-api

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: nevermade-api
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "nevermade-api"
          target: "/home/nevermade-api/nevermade-api"
          timeout: 60s # Increased timeout
          command_timeout: 20m # Increased command timeout

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: nevermade-api
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl restart nevermade-api
          timeout: 60s
