name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build
        run: go build -o nevermade-api

      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: nevermade-api
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: echo "SSH connection successful"
          timeout: 60s

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: nevermade-api
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "nevermade-api"
          target: "/opt/nevermade/api"
          timeout: 60s
          command_timeout: 20m
          debug: true

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: nevermade-api
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl restart nevermade-api
          timeout: 60s
