name: Deploy Go API

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23" # Specify the Go version you're using

      - name: Build API
        run: |
          go build -o llm-chat-api

      - name: Prepare Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/nevermade-api/projects/llm-chat-api
            chmod 755 /home/nevermade-api/projects/llm-chat-api

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "llm-chat-api"
          target: "/home/nevermade-api/projects/llm-chat-api"

      - name: Restart API Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/nevermade-api/projects/llm-chat-api
            sudo systemctl restart llm-chat-api.service
